from PIL import Image,ImageFilter

img= Image.open('./Pokedex/pikachu.jpg')
print(img)
print(img.format)
print("*****************************")
print(img.size)
print("*****************************")  
print(img.mode)
print("*****************************")
print(img.info)
print("*****************************")
print(dir(img))
print("*****************************")
filtered_img= img.filter(ImageFilter.BLUR)
print(filtered_img)
print("*****************************")
print(filtered_img.size)
print("*****************************")
print(filtered_img.mode)
print("*****************************")
print(filtered_img.info)
print("*****************************")
print(dir(filtered_img))
print("*****************************")
filtered_img.show()
print("*****************************")
sharpen_image= img.filter(ImageFilter.SHARPEN)
sharpen_image.show()
print("*****************************")
sharpen_image.save('./Pokedex/sharpen_image.png')

rotated_image= img.rotate(90)
rotated_image.show()
print("*****************************")
resized_image= img.resize((300, 300))
resized_image.show()
print("*****************************")
# rotated_image.save('./Pokedex/rotated_image.png')
# print(filtered_img.format)
# print("*****************************")
# print(filtered_img.size)
# print("*****************************")
# print(filtered_img.mode)
# print("*****************************")
# print(filtered_img.info)
# print("*****************************")

# img.save('./Pokedex/pikachu.png')

# img.resize((300, 300))

# img.rotate(45)